version: '3.2'
services:
  legacywebshop:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8888:8080"
    environment:
      USERMANAGEMENT_DB_PASSWORD: password

  web-shop-db-image:
    build:
      context: ./
      dockerfile: ./docker/DockerfileMySQL
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: default
      MYSQL_PRODUCTS_PASSWORD: password
      MYSQL_CATEGORIES_PASSWORD: password
      MYSQL_USERMANAGEMENT_PASSWORD: password
    ports:
      - "3306:3306"

  product-service:
    build:
      context: ../products-service
      dockerfile: ../products-service/Dockerfile
    environment:
      category-service.base-url: "http://categories-service:8080"
      spring.datasource.url: "jdbc:mysql://web-shop-db-image:3306/products"
    ports:
      - "8081:8080"

  categories-service:
    build:
      context: ../categories-service
      dockerfile: ../categories-service/Dockerfile
    environment:
      products-service.base-url: "http://products-service:8080"
      spring.datasource.url: "jdbc:mysql://web-shop-db-image:3306/categories"
    ports:
      - "8082:8080"
